packages:
  - packages/*
  - packages/examples/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - bigint-buffer
  - bufferutil
  - esbuild
  - keccak
  - lmdb
  - msgpackr-extract
  - msw
  - protobufjs
  - sharp
  - tiny-secp256k1
  - utf-8-validate

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - "@stakekit/rainbowkit"