import { vars } from "./contract.css";

export const unresponsiveProperties = {
  position: ["relative", "absolute", "sticky", "fixed"],
  opacity: [0, 0.1, 0.5, 1],
  zIndex: vars.zIndices,
  fontWeight: vars.fontWeight,
  border: ["none"],
  borderRadius: vars.borderRadius.baseContract,
  textAlign: ["left", "center", "right", "end"],
  flex: [1, 2, 3, 4, 5],
  flexGrow: [0, 1, 2, 3],
  flexShrink: [0, 1, 2, 3],
  lineHeight: vars.lineHeight,
  letterSpacing: vars.letterSpacing,
  borderWidth: [0.5, 1, 2, 3],
  borderStyle: ["solid"],
  overflowWrap: ["normal", "break-word", "anywhere"],
} as const;

export const responsiveProperties = {
  display: ["block", "inline", "inline-block", "flex", "inline-flex", "none"],
  fontSize: vars.fontSize,
  margin: vars.space,
  marginTop: vars.space,
  marginBottom: vars.space,
  marginRight: vars.space,
  marginLeft: vars.space,
  padding: vars.space,
  paddingTop: vars.space,
  paddingBottom: vars.space,
  paddingRight: vars.space,
  paddingLeft: vars.space,
  alignItems: ["flex-start", "flex-end", "center", "stretch"],
  alignSelf: ["auto", "flex-start", "flex-end", "center", "stretch"],
  justifyContent: ["flex-start", "flex-end", "center", "space-between"],
  flexDirection: ["row", "column", "row-reverse", "column-reverse"],
  flexWrap: ["wrap", "nowrap"],
  height: vars.space,
  width: vars.space,
  minWidth: vars.space,
  minHeight: vars.space,
  maxWidth: vars.space,
  maxHeight: vars.space,
  gap: vars.space,
} as const;
