import { spawn } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

type JsonPatchOperation = {
  op: "replace";
  path: string;
  value: unknown;
};

type SpecOutputConfig = {
  format: "httpclient" | "httpclient-type-only";
  outputPath: string;
  schemaOnly?: boolean;
};

type SpecConfig = {
  name: string;
  outputs: ReadonlyArray<SpecOutputConfig>;
  patches: JsonPatchOperation[];
  prepareSpec?: (contents: string) => string;
  specFileName: string;
  url: string;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const widgetRoot = path.resolve(scriptDir, "..");
const workspaceRoot = path.resolve(widgetRoot, "../..");
const binaryPath = (root: string, name: string) =>
  path.join(
    root,
    "node_modules/.bin",
    `${name}${process.platform === "win32" ? ".CMD" : ""}`
  );
const openApiGeneratorBin = binaryPath(widgetRoot, "openapigen");
const biomeBin = binaryPath(workspaceRoot, "biome");
const generatedFileHeader = [
  "// @ts-nocheck",
  "// biome-ignore-all lint: generated by Effect OpenAPI",
  "",
].join("\n");

const specs: SpecConfig[] = [
  {
    name: "LegacyApi",
    url: process.env.LEGACY_API_SPEC_URL ?? "https://api.stakek.it/docs.yaml",
    specFileName: "legacy-api.yaml",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/legacy.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/legacy-schema.ts"),
        schemaOnly: true,
      },
    ],
    patches: [
      // Upstream currently declares regionCode as an object, but production
      // payloads and widget geo-block handling use it as a string.
      {
        op: "replace",
        path: "/components/schemas/GeolocationError/properties/regionCode/type",
        value: "string",
      },
    ],
  },
  {
    name: "YieldApi",
    url:
      process.env.YIELD_API_SPEC_URL ?? "https://api.stg.yield.xyz/docs.yaml",
    specFileName: "yield-api.yaml",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/yield.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/yield-schema.ts"),
        schemaOnly: true,
      },
    ],
    patches: [
      // The spec marks these date-time fields as nullable, but openapigen beta
      // currently drops null for nullable date-time strings. Replacing the
      // property without format preserves the production response shape.
      {
        op: "replace",
        path: "/components/schemas/TransactionDto/properties/broadcastedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the transaction was broadcasted to the network",
        },
      },
      {
        op: "replace",
        path: "/components/schemas/ActionDto/properties/completedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the action was completed",
        },
      },
    ],
  },
  {
    name: "BorrowApi",
    url:
      process.env.BORROW_API_SPEC_URL ?? "https://borrow.yield.xyz/docs.json",
    specFileName: "borrow-api.json",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/borrow-client.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/borrow.ts"),
        schemaOnly: true,
      },
    ],
    patches: [],
    prepareSpec: (contents) =>
      contents.replaceAll(
        '"allOf":[{"$ref":"#/components/schemas/ArgumentSchemaPropertyDto"}]',
        '"type":"object"'
      ),
  },
];

const run = async (
  command: string,
  args: string[],
  options?: { input?: string }
) =>
  new Promise<{ stderr: string; stdout: string }>((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: widgetRoot,
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }

      reject(
        new Error(
          [
            `Command failed: ${command} ${args.join(" ")}`,
            `Exit code: ${code}`,
            stderr.trim(),
          ]
            .filter(Boolean)
            .join("\n")
        )
      );
    });

    if (options?.input) {
      child.stdin.write(options.input);
    }
    child.stdin.end();
  });

const fetchSpec = async (spec: SpecConfig) => {
  const response = await fetch(spec.url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${spec.name} spec from ${spec.url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
};

const extractSchemaOnlyOutput = (output: string, specName: string) => {
  const clientMarker = "\nexport interface OperationConfig {";
  const clientStart = output.indexOf(clientMarker);

  if (clientStart === -1) {
    throw new Error(
      `${specName} schema generation did not contain the expected client marker`
    );
  }

  return `${output
    .slice(0, clientStart)
    .replace(/^import \* as Data from "effect\/Data";?\r?\n/m, "")
    .replace(/^import \* as Effect from "effect\/Effect";?\r?\n/m, "")
    .replace(/^import type \{ SchemaError \} from "effect\/Schema";?\r?\n/m, "")
    .replace(
      /^import(?: type)? \* as HttpClient[^\n]+"effect\/unstable\/http\/[^\n]+\r?\n/gm,
      ""
    )
    .trimEnd()}\n`;
};

const generateSpec = async (spec: SpecConfig, tempDir: string) => {
  const specPath = path.join(tempDir, spec.specFileName);
  const patchPath = path.join(tempDir, `${spec.specFileName}.patch.json`);

  console.log(`Fetching ${spec.name} spec from ${spec.url}`);
  const specContents = await fetchSpec(spec);
  await writeFile(specPath, spec.prepareSpec?.(specContents) ?? specContents);
  await writeFile(patchPath, `${JSON.stringify(spec.patches, null, 2)}\n`);

  for (const output of spec.outputs) {
    await mkdir(path.dirname(output.outputPath), { recursive: true });

    console.log(
      `Generating ${path.relative(widgetRoot, output.outputPath)} (${output.format})`
    );
    const { stdout, stderr } = await run(openApiGeneratorBin, [
      "--spec",
      specPath,
      "--name",
      spec.name,
      "--format",
      output.format,
      "--patch",
      patchPath,
    ]);

    if (stderr.trim()) {
      console.warn(stderr.trim());
    }

    if (!stdout.trim()) {
      throw new Error(
        `${spec.name} ${output.format} generation produced empty output`
      );
    }

    const generatedOutput = output.schemaOnly
      ? extractSchemaOnlyOutput(stdout, spec.name)
      : stdout;

    await writeFile(
      output.outputPath,
      `${generatedFileHeader}${generatedOutput}`
    );
  }
};

const main = async () => {
  const tempDir = await mkdtemp(path.join(tmpdir(), "stakekit-openapi-"));
  const requestedSpecs = new Set(process.argv.slice(2));
  const selectedSpecs = requestedSpecs.size
    ? specs.filter((spec) => requestedSpecs.has(spec.name))
    : specs;

  if (!selectedSpecs.length) {
    throw new Error(
      `No OpenAPI specs matched: ${[...requestedSpecs].join(", ")}`
    );
  }

  try {
    for (const spec of selectedSpecs) {
      await generateSpec(spec, tempDir);
    }

    await run(biomeBin, [
      "check",
      "--write",
      "--unsafe",
      ...selectedSpecs.flatMap((spec) =>
        spec.outputs.map((output) =>
          path.relative(widgetRoot, output.outputPath)
        )
      ),
    ]);
  } finally {
    await rm(tempDir, { force: true, recursive: true });
  }
};

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
