import { spawn } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

type JsonPatchOperation = {
  op: "replace";
  path: string;
  value: unknown;
};

const nullableScalarPatch = ({
  description,
  example,
  property,
  schema,
  type,
}: {
  description: string;
  example: unknown;
  property: string;
  schema: string;
  type: "number" | "string";
}): JsonPatchOperation => ({
  op: "replace",
  path: `/components/schemas/${schema}/properties/${property}`,
  value: { description, example, nullable: true, type },
});

type SpecOutputConfig = {
  format: "httpclient" | "httpclient-type-only";
  outputPath: string;
  schemaOnly?: boolean;
};

type SpecConfig = {
  name: string;
  outputs: ReadonlyArray<SpecOutputConfig>;
  patches: JsonPatchOperation[];
  prepareSpec?: (contents: string) => string;
  specFileName: string;
  url: string;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const widgetRoot = path.resolve(scriptDir, "..");
const workspaceRoot = path.resolve(widgetRoot, "../..");
const binaryPath = (root: string, name: string) =>
  path.join(
    root,
    "node_modules/.bin",
    `${name}${process.platform === "win32" ? ".CMD" : ""}`
  );
const openApiGeneratorBin = binaryPath(widgetRoot, "openapigen");
const biomeBin = binaryPath(workspaceRoot, "biome");
const generatedFileHeader = [
  "// @ts-nocheck",
  "// biome-ignore-all lint: generated by Effect OpenAPI",
  "",
].join("\n");

const specs: SpecConfig[] = [
  {
    name: "LegacyApi",
    url: process.env.LEGACY_API_SPEC_URL ?? "https://api.stakek.it/docs.yaml",
    specFileName: "legacy-api.yaml",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/legacy.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/legacy-schema.ts"),
        schemaOnly: true,
      },
    ],
    patches: [
      // Upstream currently declares regionCode as an object, but production
      // payloads and widget geo-block handling use it as a string.
      {
        op: "replace",
        path: "/components/schemas/GeolocationError/properties/regionCode/type",
        value: "string",
      },
    ],
  },
  {
    name: "YieldApi",
    url:
      process.env.YIELD_API_SPEC_URL ?? "https://api.stg.yield.xyz/docs.yaml",
    specFileName: "yield-api.yaml",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/yield.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/yield-schema.ts"),
        schemaOnly: true,
      },
    ],
    patches: [
      // These DTO properties have concrete scalar types in the Yield API
      // source, but their Swagger decorators omit the explicit property type.
      // Patch the spec so openapigen does not emit `{}` placeholders.
      nullableScalarPatch({
        schema: "LiquidityStateDto",
        property: "liquidity",
        type: "string",
        description: "Available liquidity in underlying token units",
        example: "250000.00",
      }),
      nullableScalarPatch({
        schema: "LiquidityStateDto",
        property: "utilization",
        type: "string",
        description: "Utilization rate as a decimal (e.g., 0.8 = 80%)",
        example: "0.80",
      }),
      nullableScalarPatch({
        schema: "YieldFeeConfigurationDto",
        property: "managementFeeBps",
        type: "number",
        description: "Management fee in basis points",
        example: 100,
      }),
      nullableScalarPatch({
        schema: "YieldFeeConfigurationDto",
        property: "performanceFeeBps",
        type: "number",
        description: "Performance fee in basis points",
        example: 1000,
      }),
      nullableScalarPatch({
        schema: "YieldFeeConfigurationDto",
        property: "depositFeeBps",
        type: "number",
        description: "Deposit fee in basis points",
        example: 0,
      }),
      nullableScalarPatch({
        schema: "YieldFeeConfigurationDto",
        property: "allocatorVaultContractAddress",
        type: "string",
        description: "Partner allocator vault contract address",
        example: "0x80ac24aa929eaf5013f6436cda2a7ba190f5cc0b",
      }),
      nullableScalarPatch({
        schema: "ProviderDto",
        property: "tvlUsd",
        type: "string",
        description: "Total TVL across the entire provider in USD",
        example: "10,200,000",
      }),
      nullableScalarPatch({
        schema: "ValidatorProviderDto",
        property: "tvlUsd",
        type: "string",
        description: "Total TVL across the entire provider in USD",
        example: "10,200,000",
      }),
      nullableScalarPatch({
        schema: "CuratorDto",
        property: "name",
        type: "string",
        description: "Curator name",
        example: "Steakhouse Financial",
      }),
      nullableScalarPatch({
        schema: "CuratorDto",
        property: "description",
        type: "string",
        description: "Curator description",
        example: "Vault curator",
      }),
      nullableScalarPatch({
        schema: "CuratorDto",
        property: "logoURI",
        type: "string",
        description: "Curator logo URI",
        example: "https://example.com/curator.svg",
      }),
      nullableScalarPatch({
        schema: "YieldRiskCredoraDto",
        property: "rating",
        type: "string",
        description: "Credora rating",
        example: "A",
      }),
      nullableScalarPatch({
        schema: "YieldRiskCredoraDto",
        property: "score",
        type: "number",
        description: "Credora score (1-5)",
        example: 4.5,
      }),
      nullableScalarPatch({
        schema: "YieldRiskCredoraDto",
        property: "psl",
        type: "number",
        description: "Probability of Significant Loss (annualized)",
        example: 0.01,
      }),
      nullableScalarPatch({
        schema: "YieldRiskCredoraDto",
        property: "publishDate",
        type: "string",
        description: "Credora publish date",
        example: "2026-01-01",
      }),
      nullableScalarPatch({
        schema: "YieldRiskCredoraDto",
        property: "curator",
        type: "string",
        description: "Credora curator name",
        example: "Credora",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsMetricsDto",
        property: "users",
        type: "number",
        description: "Users count from Staking Rewards risk metrics",
        example: 1000,
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "rating",
        type: "string",
        description: "Staking Rewards rating",
        example: "A",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "score",
        type: "number",
        description: "Staking Rewards score (1-5)",
        example: 4,
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "potentialRating",
        type: "string",
        description: "Staking Rewards potential rating",
        example: "A+",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "potentialScore",
        type: "number",
        description: "Staking Rewards potential score (1-5)",
        example: 4.5,
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "ratedAt",
        type: "string",
        description: "Date when rating was assessed",
        example: "2026-01-01",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "ratedSince",
        type: "string",
        description: "Date since product has been rated",
        example: "2025-01-01",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "profileUrl",
        type: "string",
        description: "Staking Rewards product profile URL",
        example: "https://stakingrewards.com/provider",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "reportUrl",
        type: "string",
        description: "Staking Rewards full report URL",
        example: "https://stakingrewards.com/report",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "providerName",
        type: "string",
        description: "Staking Rewards provider name",
        example: "Provider",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "version",
        type: "string",
        description: "Staking Rewards methodology version",
        example: "v1",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "type",
        type: "string",
        description: "Staking Rewards product type",
        example: "validator",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "chain",
        type: "string",
        description: "Chain label returned by Staking Rewards",
        example: "ethereum",
      }),
      nullableScalarPatch({
        schema: "YieldRiskStakingRewardsDto",
        property: "contractAddress",
        type: "string",
        description: "Contract address returned by Staking Rewards",
        example: "0x0000000000000000000000000000000000000001",
      }),
      {
        op: "replace",
        path: "/components/schemas/BalanceDto/properties/priceRange",
        value: {
          type: "object",
          description:
            "Price range for concentrated liquidity positions in tokens[1]/tokens[0] format",
          properties: {
            min: { type: "string" },
            max: { type: "string" },
          },
          required: ["min", "max"],
        },
      },
      // The spec marks these date-time fields as nullable, but openapigen beta
      // currently drops null for nullable date-time strings. Replacing the
      // property without format preserves the production response shape.
      {
        op: "replace",
        path: "/components/schemas/TransactionDto/properties/broadcastedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the transaction was broadcasted to the network",
        },
      },
      {
        op: "replace",
        path: "/components/schemas/ActionDto/properties/completedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the action was completed",
        },
      },
    ],
  },
  {
    name: "BorrowApi",
    url:
      process.env.BORROW_API_SPEC_URL ?? "https://borrow.yield.xyz/docs.json",
    specFileName: "borrow-api.json",
    outputs: [
      {
        format: "httpclient-type-only",
        outputPath: path.join(widgetRoot, "src/generated/api/borrow-client.ts"),
      },
      {
        format: "httpclient",
        outputPath: path.join(widgetRoot, "src/generated/api/borrow.ts"),
        schemaOnly: true,
      },
    ],
    patches: [],
    prepareSpec: (contents) =>
      contents.replaceAll(
        '"allOf":[{"$ref":"#/components/schemas/ArgumentSchemaPropertyDto"}]',
        '"type":"object"'
      ),
  },
];

const run = async (
  command: string,
  args: string[],
  options?: { input?: string }
) =>
  new Promise<{ stderr: string; stdout: string }>((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: widgetRoot,
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }

      reject(
        new Error(
          [
            `Command failed: ${command} ${args.join(" ")}`,
            `Exit code: ${code}`,
            stderr.trim(),
          ]
            .filter(Boolean)
            .join("\n")
        )
      );
    });

    if (options?.input) {
      child.stdin.write(options.input);
    }
    child.stdin.end();
  });

const fetchSpec = async (spec: SpecConfig) => {
  const response = await fetch(spec.url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${spec.name} spec from ${spec.url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
};

const extractSchemaOnlyOutput = (output: string, specName: string) => {
  const clientMarker = "\nexport interface OperationConfig {";
  const clientStart = output.indexOf(clientMarker);

  if (clientStart === -1) {
    throw new Error(
      `${specName} schema generation did not contain the expected client marker`
    );
  }

  return `${output
    .slice(0, clientStart)
    .replace(/^import \* as Data from "effect\/Data";?\r?\n/m, "")
    .replace(/^import \* as Effect from "effect\/Effect";?\r?\n/m, "")
    .replace(/^import type \{ SchemaError \} from "effect\/Schema";?\r?\n/m, "")
    .replace(
      /^import(?: type)? \* as HttpClient[^\n]+"effect\/unstable\/http\/[^\n]+\r?\n/gm,
      ""
    )
    .trimEnd()}\n`;
};

const generateSpec = async (spec: SpecConfig, tempDir: string) => {
  const specPath = path.join(tempDir, spec.specFileName);
  const patchPath = path.join(tempDir, `${spec.specFileName}.patch.json`);

  console.log(`Fetching ${spec.name} spec from ${spec.url}`);
  const specContents = await fetchSpec(spec);
  await writeFile(specPath, spec.prepareSpec?.(specContents) ?? specContents);
  await writeFile(patchPath, `${JSON.stringify(spec.patches, null, 2)}\n`);

  for (const output of spec.outputs) {
    await mkdir(path.dirname(output.outputPath), { recursive: true });

    console.log(
      `Generating ${path.relative(widgetRoot, output.outputPath)} (${output.format})`
    );
    const { stdout, stderr } = await run(openApiGeneratorBin, [
      "--spec",
      specPath,
      "--name",
      spec.name,
      "--format",
      output.format,
      "--patch",
      patchPath,
    ]);

    if (stderr.trim()) {
      console.warn(stderr.trim());
    }

    if (!stdout.trim()) {
      throw new Error(
        `${spec.name} ${output.format} generation produced empty output`
      );
    }

    const generatedOutput = output.schemaOnly
      ? extractSchemaOnlyOutput(stdout, spec.name)
      : stdout;

    await writeFile(
      output.outputPath,
      `${generatedFileHeader}${generatedOutput}`
    );
  }
};

const main = async () => {
  const tempDir = await mkdtemp(path.join(tmpdir(), "stakekit-openapi-"));
  const requestedSpecs = new Set(process.argv.slice(2));
  const selectedSpecs = requestedSpecs.size
    ? specs.filter((spec) => requestedSpecs.has(spec.name))
    : specs;

  if (!selectedSpecs.length) {
    throw new Error(
      `No OpenAPI specs matched: ${[...requestedSpecs].join(", ")}`
    );
  }

  try {
    for (const spec of selectedSpecs) {
      await generateSpec(spec, tempDir);
    }

    await run(biomeBin, [
      "check",
      "--write",
      "--unsafe",
      ...selectedSpecs.flatMap((spec) =>
        spec.outputs.map((output) =>
          path.relative(widgetRoot, output.outputPath)
        )
      ),
    ]);
  } finally {
    await rm(tempDir, { force: true, recursive: true });
  }
};

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
