import { spawn } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

type JsonPatchOperation = {
  op: "replace";
  path: string;
  value: unknown;
};

type SpecConfig = {
  name: string;
  outputPath: string;
  patches: JsonPatchOperation[];
  specFileName: string;
  url: string;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const widgetRoot = path.resolve(scriptDir, "..");
const generatedFileHeader = [
  "// @ts-nocheck",
  "// biome-ignore-all lint: generated by Effect OpenAPI",
  "",
].join("\n");

const specs: SpecConfig[] = [
  {
    name: "LegacyApi",
    url: process.env.LEGACY_API_SPEC_URL ?? "https://api.stakek.it/docs.yaml",
    specFileName: "legacy-api.yaml",
    outputPath: path.join(widgetRoot, "src/generated/api/legacy.ts"),
    patches: [
      // Upstream currently declares regionCode as an object, but production
      // payloads and widget geo-block handling use it as a string.
      {
        op: "replace",
        path: "/components/schemas/GeolocationError/properties/regionCode/type",
        value: "string",
      },
    ],
  },
  {
    name: "YieldApi",
    url:
      process.env.YIELD_API_SPEC_URL ?? "https://api.stg.yield.xyz/docs.yaml",
    specFileName: "yield-api.yaml",
    outputPath: path.join(widgetRoot, "src/generated/api/yield.ts"),
    patches: [
      // The spec marks these date-time fields as nullable, but openapigen beta
      // currently drops null for nullable date-time strings. Replacing the
      // property without format preserves the production response shape.
      {
        op: "replace",
        path: "/components/schemas/TransactionDto/properties/broadcastedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the transaction was broadcasted to the network",
        },
      },
      {
        op: "replace",
        path: "/components/schemas/ActionDto/properties/completedAt",
        value: {
          type: "string",
          nullable: true,
          description: "When the action was completed",
        },
      },
    ],
  },
];

const run = async (
  command: string,
  args: string[],
  options?: { input?: string }
) =>
  new Promise<{ stderr: string; stdout: string }>((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: widgetRoot,
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
        return;
      }

      reject(
        new Error(
          [
            `Command failed: ${command} ${args.join(" ")}`,
            `Exit code: ${code}`,
            stderr.trim(),
          ]
            .filter(Boolean)
            .join("\n")
        )
      );
    });

    if (options?.input) {
      child.stdin.write(options.input);
    }
    child.stdin.end();
  });

const fetchSpec = async (spec: SpecConfig) => {
  const response = await fetch(spec.url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${spec.name} spec from ${spec.url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
};

const generateSpec = async (spec: SpecConfig, tempDir: string) => {
  const specPath = path.join(tempDir, spec.specFileName);
  const patchPath = path.join(tempDir, `${spec.specFileName}.patch.json`);

  console.log(`Fetching ${spec.name} spec from ${spec.url}`);
  await writeFile(specPath, await fetchSpec(spec));
  await writeFile(patchPath, `${JSON.stringify(spec.patches, null, 2)}\n`);
  await mkdir(path.dirname(spec.outputPath), { recursive: true });

  console.log(`Generating ${path.relative(widgetRoot, spec.outputPath)}`);
  const { stdout, stderr } = await run("pnpm", [
    "exec",
    "openapigen",
    "--spec",
    specPath,
    "--name",
    spec.name,
    "--format",
    "httpclient-type-only",
    "--patch",
    patchPath,
  ]);

  if (stderr.trim()) {
    console.warn(stderr.trim());
  }

  if (!stdout.trim()) {
    throw new Error(`${spec.name} generation produced empty output`);
  }

  await writeFile(spec.outputPath, `${generatedFileHeader}${stdout}`);
};

const main = async () => {
  const tempDir = await mkdtemp(path.join(tmpdir(), "stakekit-openapi-"));

  try {
    for (const spec of specs) {
      await generateSpec(spec, tempDir);
    }

    await run("pnpm", [
      "exec",
      "biome",
      "check",
      "--write",
      "--unsafe",
      ...specs.map((spec) => path.relative(widgetRoot, spec.outputPath)),
    ]);
  } finally {
    await rm(tempDir, { force: true, recursive: true });
  }
};

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
