// Generated by get-errors.js script.
// Do not edit manually.

export const errorsSet = new Set([
  "MissingArgumentsError",
  "MinimumAmountNotReached",
  "YieldUnderMaintenanceError",
  "InsufficientFundsError",
  "BalanceUnavailableError",
  "GasPriceUnavailableError",
  "NotImplementedError",
  "TokenNotFoundError",
  "BroadcastTransactionError",
  "MissingGasPriceStrategyError",
  "SubstrateMalformedTransactionHashError",
  "TronMaximumAmountOfValidatorsExceededError",
  "SubstratePoolNotFoundError",
  "SubstrateBondedAmountTooLowError",
  "TronMissingResourceTypeArgumentError",
  "AaveV3PoolFrozenError",
  "AaveV3TokenPairNotFoundError",
  "YearnVaultAtMaxCapacityError",
  "StETHNoWithdrawalRequestsFoundError",
  "MorphoLendingPoolPausedError",
  "NonceUnavailableError",
  "CosmosAcccountNotFoundError",
  "AvalancheMissingAdditionalAddressesArgumentError",
  "AvalancheValidatorInfoNotFoundError",
  "SolanaTransactionSignatureVerificationFailureError",
  "SolanaUnableTocreateStakeAccountError",
  "SolanaStakeAmountTooLowError",
  "SolanaUnstakeAmountTooLowError",
  "SolanaStakeAccountsNotFoundError",
  "SolanaEligibleStakeAccountsNotFoundError",
  "TezosNoBalanceDelegatedError",
  "TezosMissingPubkeyArgumentError",
  "TezosEstimateRevealGasLimitError",
  "TezosBalanceAlreadyDelegatedError",
  "BinanceAccountNotFoundError",
  "BinanceMissingAccountNumberOrSequenceError",
]);

export type ErrorsSet =
  | "MissingArgumentsError"
  | "MinimumAmountNotReached"
  | "YieldUnderMaintenanceError"
  | "InsufficientFundsError"
  | "BalanceUnavailableError"
  | "GasPriceUnavailableError"
  | "NotImplementedError"
  | "TokenNotFoundError"
  | "BroadcastTransactionError"
  | "MissingGasPriceStrategyError"
  | "SubstrateMalformedTransactionHashError"
  | "TronMaximumAmountOfValidatorsExceededError"
  | "SubstratePoolNotFoundError"
  | "SubstrateBondedAmountTooLowError"
  | "TronMissingResourceTypeArgumentError"
  | "AaveV3PoolFrozenError"
  | "AaveV3TokenPairNotFoundError"
  | "YearnVaultAtMaxCapacityError"
  | "StETHNoWithdrawalRequestsFoundError"
  | "MorphoLendingPoolPausedError"
  | "NonceUnavailableError"
  | "CosmosAcccountNotFoundError"
  | "AvalancheMissingAdditionalAddressesArgumentError"
  | "AvalancheValidatorInfoNotFoundError"
  | "SolanaTransactionSignatureVerificationFailureError"
  | "SolanaUnableTocreateStakeAccountError"
  | "SolanaStakeAmountTooLowError"
  | "SolanaUnstakeAmountTooLowError"
  | "SolanaStakeAccountsNotFoundError"
  | "SolanaEligibleStakeAccountsNotFoundError"
  | "TezosNoBalanceDelegatedError"
  | "TezosMissingPubkeyArgumentError"
  | "TezosEstimateRevealGasLimitError"
  | "TezosBalanceAlreadyDelegatedError"
  | "BinanceAccountNotFoundError"
  | "BinanceMissingAccountNumberOrSequenceError";
