name: "Publish package to npm"

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/composite_actions/initial_setup

      - name: Build
        run: yarn workspace @stakekit/widget build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
