name: "Publish package to npm"

on:
  workflow_dispatch:

jobs:
  build-and-publish-release:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    environment: production
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/composite_actions/initial_setup

      - name: Set npm auth token
        run: |
          echo npmAuthToken: "$NPM_TOKEN" >> ./.yarnrc.yml
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn npm publish
